site_name: Network Security Game
theme:
  name: material
  user_color_mode_toggle: true

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Architecture: architecture.md
  - Configuration: configuration.md
  - Global Defender: global_defender.md
  - API Reference:
    - Game Components: game_components.md
    - Base Agent: base_agent.md
    - Agent Server: agent_server.md
    - Game Coordinator: game_coordinator.md
    - Configuration Manager: configuration_manager.md
    - Config Parser: config_parser.md
    - Worlds:
      - NetSecGame: NetSecGame.md
      - WhiteBoxNetSecGame: WhiteBoxNetSecGame.md
    - Utils:
      - Utils: utils.md
      - Trajectory Recorder: trajectory_recorder.md
      

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 2
            show_root_heading: true
            show_signature: false
            show_source: true
            members_order: alphabetical
            merge_init_into_class: true
            filters: []
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.highlight
  - admonition

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js